routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'AdminController@index']);

    /*
     * Users
     */
    Route::get('users/sort', ['as' => 'admin.users.sort', 'uses' => 'UserController@sort']);
    Route::get('users/search', ['as' => 'admin.users.search', 'uses' => 'UserController@search']);
    Route::resource('users', 'UserController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Categories
     */
    Route::get('categories/sort', ['as' => 'admin.categories.sort', 'uses' => 'CategoryController@sort']);
    Route::get('categories/search', ['as' => 'admin.categories.search', 'uses' => 'CategoryController@search']);
    Route::resource('categories', 'CategoryController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Posts
     */
    Route::get('posts/sort', ['as' => 'admin.posts.sort', 'uses' => 'PostController@sort']);
    Route::get('posts/search', ['as' => 'admin.posts.search', 'uses' => 'PostController@search']);
    Route::resource('posts', 'PostController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Tags
     */
    Route::get('tags/sort', ['as' => 'admin.tags.sort', 'uses' => 'TagController@sort']);
    Route::get('tags/search', ['as' => 'admin.tags.search', 'uses' => 'TagController@search']);
    Route::resource('tags', 'TagController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Laravel\Scout\Searchable;

class User extends Authenticatable
{
    use Notifiable, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Contracts\ImageContract;
use App\Repositories\UserRepository;

class UserController extends Controller
{
    protected $user;

    public function __construct(UserRepository $userRepository)
    {
        $this->user = $userRepository;
    }

    public function index()
    {
        $users = $this->user->index(10);

        return view('admin.users.index', $users);
    }

    public function edit($id)
    {
        $values = $this->user->edit($id);

        return view('admin.users.edit', $values);
    }

    public function update(Request $request, ImageContract $image, $id)
    {
        $result = $this->user->updateUser($request, $image, $id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Данные успешно изменены!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось внести изменения!');
        }

        return $redirect;
    }

    public function destroy($id)
    {
        if ($this->user->delete($id)) {
            $redirect = redirect()->back()->with('success', 'Пользователь удален!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось удалить пользователя!');
        }

        return $redirect;
    }

    public function sort(Request $request)
    {
        $result = $this->user->sort($request,10, ['roles']);

        return view('admin.users.index', $result);
    }

    public function search(Request $request)
    {
        $result = $this->user->search($request, 10);

        return view('admin.users.index', $result);
    }

}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.users.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Редактирование пользователя </h5>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label>Image:</label>
                            <div class="row">
                                <div class="col-md-3">
                                    @if(!empty($user->image))
                                        <img id="outImage" src="{{ asset($user->image)}}" width="100%">
                                    @else
                                        <img id="outImage" src="{{ asset('images/default.jpg')}}" width="100%">
                                    @endif
                                </div>
                            </div>
                            <input type="file" id="image" name="image" class="btn">
                        </div>

                        <div class="form-group">
                            <label>Name:</label>
                            <input type="text" class="form-control" name="name" placeholder="name" value="{{ $user->name }}">
                        </div>

                        <div class="form-group">
                            <label>Email:</label>
                            <input type="email" class="form-control" name="email" placeholder="email" value="{{ $user->email }}">
                        </div>

                        <div class="form-group">
                            <label>Права пользователя:</label>
                            @foreach($roles as $role)
                                <div class="checkbox checkbox-switchery">
                                    <label>
                                        @if($role->users()->where('user_id', $user->id)->first() !== null)
                                            <input type="checkbox" name="{{ $role->name }}" class="switchery" checked>
                                        @else
                                            <input type="checkbox" name="{{ $role->name }}" class="switchery" unchecked>
                                        @endif
                                        {{ $role->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#image').change(function (e) {
                var file = e.target.files[0];
                if (!file.type.match('image.*')) {
                    alert("Image only please....");
                }
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#outImage').attr('src', e.target.result);
                };
                reader.readAsDataURL(file);
            });
        });
    </script>

@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@push('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_notifications_other.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/datatables_basic.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_inputs.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js') }}"></script>
@endpush

@section('content')

    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="row">
                
                <div class="col-md-9">
                    <h5 class="panel-title"><a href="{{ route('admin.users.index') }}">Пользователи</a></h5>
                </div>
                
                <div class="col-md-3">
                    <form action="{{ route('admin.users.search') }}" method="GET">
                        <div class="has-feedback-left">
                            <input type="text" name="query" class="form-control" placeholder="{{ isset($query) ? $query : 'поиск' }}">
                            <div class="form-control-feedback">
                                <i class="icon-search4 text-size-base"></i>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @if(!isset($query) || isset($type))
                            <a href="{{ route('admin.users.sort', ['name' => 'id', 'type' => isset($type) ? $type : '']) }}">ID</a>
                        @else
                            ID
                        @endif
                    </th>
                    <th>Image</th>
                    <th>
                        @if(!isset($query) || isset($type))
                            <a href="{{ route('admin.users.sort', ['name' => 'name', 'type' => isset($type) ? $type : '']) }}">Name</a>
                        @else
                            Name
                        @endif
                    </th>
                    <th>
                        @if(!isset($query) || isset($type))
                            <a href="{{ route('admin.users.sort', ['name' => 'email', 'type' => isset($type) ? $type : '']) }}">Email</a>
                        @else
                            Email
                        @endif
                    </th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th>Status</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach($result as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>
                            @if(!empty($user->image))
                                <img src="{{ asset($user->image) }}" width="100px">
                            @else
                                <img src="{{ asset('images/default.jpg') }}" width="100px">
                            @endif
                        </td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at }}</td>
                        <td>{{ $user->updated_at }}</td>
                        <td>
                            @foreach($user->roles as $role)
                                @if($role->name == 'admin')
                                    <span class="label label-danger">{{ $role->name }}</span>
                                @elseif($role->name == 'moderator')
                                    <span class="label label-primary">{{ $role->name }}</span>
                                @endif
                            @endforeach
                        </td>
                        <td class="text-center">
                            <div class="media-right media-middle" style="float: right">
                                <ul class="icons-list icons-list-extended text-nowrap">
                                    <li><a href="{{ route('admin.users.edit', ['id' => $user->id]) }}" class="edit"><button class="btn btn-primary"><i class="icon-pencil5"></i></button></a></li>
                                    <li>
                                        <form action="{{ route('admin.users.destroy', ['id' => $user->id]) }}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('delete') }}
                                            <button type="submit" class="btn btn-danger delete"><i class="icon-trash-alt"></i></button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>

        <div class="panel-footer">
            <div style="text-align: center">
                {{ $result->links() }}
            </div>
        </div>
    </div>
    <!-- /basic datatable -->

@endsection