routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'AdminController@index']);

    /*
     * Users
     */
    Route::get('users/sort', ['as' => 'admin.users.sort', 'uses' => 'UserController@sort']);
    Route::get('users/search', ['as' => 'admin.users.search', 'uses' => 'UserController@search']);
    Route::resource('users', 'UserController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Categories
     */
    Route::get('categories/sort', ['as' => 'admin.categories.sort', 'uses' => 'CategoryController@sort']);
    Route::get('categories/search', ['as' => 'admin.categories.search', 'uses' => 'CategoryController@search']);
    Route::resource('categories', 'CategoryController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Posts
     */
    Route::get('posts/sort', ['as' => 'admin.posts.sort', 'uses' => 'PostController@sort']);
    Route::get('posts/search', ['as' => 'admin.posts.search', 'uses' => 'PostController@search']);
    Route::resource('posts', 'PostController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Tags
     */
    Route::get('tags/sort', ['as' => 'admin.tags.sort', 'uses' => 'TagController@sort']);
    Route::get('tags/search', ['as' => 'admin.tags.search', 'uses' => 'TagController@search']);
    Route::resource('tags', 'TagController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);


});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Post extends Model
{
    use Searchable;

    protected $fillable = [
        'title',
        'text',
        'image',
        'description',
        'category_id',
        'tag_id',
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;

use App\Repositories\PostRepository;
use App\Helpers\Contracts\ImageContract;

class PostController extends Controller
{
    protected $post;

    public function __construct(PostRepository $postRepository)
    {
        $this->post = $postRepository;
    }

    public function index()
    {
        $values = $this->post->index(10);

        return view('admin.posts.index', $values);
    }

    public function create()
    {
        $result = $this->post->createPost();

        return view('admin.posts.create', $result);
    }

    public function store(PostRequest $postRequest, ImageContract $image)
    {
        $result = $this->post->storePost($postRequest, $image);

        if ($result) {
            $redirect = redirect()->route('admin.posts.index')->with('success', 'Пост успешно создан!');
        } else {
            $redirect = redirect()->route('admin.posts.index')->with('error', 'Не удалось создать пост!');
        }

        return $redirect;
    }

    public function edit($id)
    {
        $result = $this->post->edit($id);

        return view('admin.posts.edit', $result);
    }

    public function update(PostRequest $postRequest, ImageContract $image, $id)
    {
        $result = $this->post->updatePost($postRequest, $image, $id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Пост успешно изменен!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось изменить пост!');
        }

        return $redirect;
    }

    public function destroy($id)
    {
        $result = $this->post->delete($id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Пост удален!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось удалить пост!');
        }

        return $redirect;
    }

    public function sort(Request $request)
    {
        $result = $this->post->sort($request, 10, ['category', 'tags']);

        return view('admin.posts.index', $result);
    }

    public function search(Request $request)
    {
        $result = $this->post->search($request, 10);

        return view('admin.posts.index', $result);
    }

}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_multiselect.js') }}"></script>
@endsection

@section('content')

    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.posts.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}

                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Создание поста</h5>
                    </div>

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-3">
                                <label>Миниатюра к посту</label>
                                <img id="outImage" src="{{ asset('images/default.jpg')}}" width="100%">
                                <input type="file" id="image" name="image" class="btn">
                                @if ($errors->has('image'))
                                    <span class="alert-danger">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-9">
                                <div class="form-group">
                                    <label>Заголовок</label>
                                    <input type="text" class="form-control" name="title" placeholder="Введите заголовок к посту" value="{{ old('title') }}">
                                    @if ($errors->has('title'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Категория поста</label>
                                    <select name="category_id" class="bootstrap-select" data-live-search="true" data-width="100%">
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Содержимое поста</label>
                                    <textarea name="text" id="editor-text" rows="4" cols="4">{{ old('text') }}</textarea>
                                    @if ($errors->has('text'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('text') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Короткое описание поста</label>
                                    <textarea name="description" id="editor-description" style="width: 100%" >{{ old('description') }}</textarea>
                                    @if ($errors->has('description'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Теги к посту</label>

                                    <div class="multi-select-full">
                                        <select class="multiselect-filtering" multiple="multiple" name="tag_ids[]">
                                            @foreach($tags as $tag)
                                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    @if ($errors->has('category_id'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#image').change(function (e) {
                var file = e.target.files[0];
                if (!file.type.match('image.*')) {
                    alert("Image only please....");
                }
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#outImage').attr('src', e.target.result);
                };
                reader.readAsDataURL(file);
            });
        });

        CKEDITOR.replace( 'editor-text' );
        CKEDITOR.replace( 'editor-description' );
    </script>

@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_multiselect.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_multiselect.js') }}"></script>
@endsection

@section('content')

    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.post.update', ['id' => $post->id]) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Создание поста</h5>
                    </div>

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-3">
                                <label>Миниатюра к посту</label>
                                @if(isset($post->image))
                                    <img id="outImage" src="{{ asset($post->image) }}" width="100%">
                                @else
                                    <img id="outImage" src="{{ asset('images/default.jpg') }}" width="100%">
                                @endif
                                <input type="file" id="image" name="image" class="btn">
                                @if ($errors->has('image'))
                                    <span class="alert-danger">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="col-md-9">
                                <div class="form-group">
                                    <label>Заголовок</label>
                                    <input type="text" class="form-control" name="title" placeholder="Введите заголовок к посту" value="{{ $post->title }}">
                                    @if ($errors->has('title'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Категория поста</label>
                                    <select name="category_id" class="bootstrap-select" data-live-search="true" data-width="100%">
                                        @foreach($categories as $category)
                                            @if($post->category->id == $category->id)
                                                <option value="{{ $post->category->id }}" selected>{{ $post->category->name }}</option>
                                            @else
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category_id'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Содержимое поста</label>
                                    <textarea name="text" id="editor-text" rows="4" cols="4">{{ $post->text }}</textarea>
                                    @if ($errors->has('text'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('text') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Короткое описание поста</label>
                                    <textarea name="description" id="editor-description" style="width: 100%" >{{ $post->description }}</textarea>
                                    @if ($errors->has('description'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Теги к посту</label>

                                    <div class="multi-select-full">
                                        <select class="multiselect-filtering" multiple="multiple" name="tag_ids[]">
                                            @foreach($tags as $tag)
                                                @if($post->tags->contains('id', $tag->id))
                                                    <option value="{{ $tag->id }}" selected>{{ $tag->name }}</option>
                                                @else
                                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>

                                    @if ($errors->has('category_id'))
                                        <span class="alert-danger">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#image').change(function (e) {
                var file = e.target.files[0];
                if (!file.type.match('image.*')) {
                    alert("Image only please....");
                }
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#outImage').attr('src', e.target.result);
                };
                reader.readAsDataURL(file);
            });
        });

        CKEDITOR.replace( 'editor-text' );
        CKEDITOR.replace( 'editor-description' );
    </script>

@endsection

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.app')

@push('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/core.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/effects.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/interactions.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/extensions/cookie.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/trees/fancytree_all.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/trees/fancytree_childcounter.js') }}"></script>

    <script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_notifications_other.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/datatables_basic.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_inputs.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/extra_trees.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js') }}"></script>
@endpush

@section('content')

    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="row">

                <div class="col-md-3">
                    <h5 class="panel-title"><a href="{{ route('admin.posts.index') }}">Посты</a></h5>
                </div>

                <div class="col-md-6">
                    <a href="{{ route('admin.posts.create') }}" class="btn btn-success">Новый пост</a>
                </div>

                <div class="col-md-3">
                    <form action="{{ route('admin.posts.search') }}" method="GET">
                        <div class="has-feedback-left">
                            <input type="text" name="query" class="form-control" placeholder="{{ isset($query) ? $query : 'поиск' }}">
                            <div class="form-control-feedback">
                                <i class="icon-search4 text-size-base"></i>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.posts.sort', ['name' => 'id', 'type' => isset($type) ? $type : '']) }}">ID</a>
                    @else
                        ID
                    @endif
                </th>
                <th>Image</th>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.posts.sort', ['name' => 'title', 'type' => isset($type) ? $type : '']) }}">Title</a>
                    @else
                        Title
                    @endif
                </th>
                <th>Category</th>
                <th>Description</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($result as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>
                        @if(!empty($post->image))
                            <img src="{{ asset($post->image) }}" width="100px">
                        @else
                            <img src="{{ asset('images/default.jpg') }}" width="100px">
                        @endif
                    </td>
                    <td>{{ $post->title }}</td>

                    @if(isset($post->category->name))
                        <td>{{ $post->category->name }}</td>
                    @else
                        <td>Это родительская категория</td>
                    @endif

                    <td>{!! $post->description !!}</td>
                    <td>{{ $post->created_at }}</td>
                    <td>{{ $post->updated_at }}</td>
                    <td class="text-center">
                        <div class="media-right media-middle" style="float: right">
                            <ul class="icons-list icons-list-extended text-nowrap">
                                <li><a href="{{ route('admin.posts.edit', ['id' => $post->id]) }}" class="edit"><button class="btn btn-primary"><i class="icon-pencil5"></i></button></a></li>
                                <li>
                                    <form action="{{ route('admin.posts.destroy', ['id' => $post->id]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                        <button type="submit" class="btn btn-danger delete"><i class="icon-trash-alt"></i></button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>

        <div class="panel-footer">
            <div style="text-align: center">
                {{ $result->links() }}
            </div>
        </div>
    </div>
    <!-- /basic datatable -->

@endsection