routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'AdminController@index']);

    /*
     * Users
     */
    Route::get('users/sort', ['as' => 'admin.users.sort', 'uses' => 'UserController@sort']);
    Route::get('users/search', ['as' => 'admin.users.search', 'uses' => 'UserController@search']);
    Route::resource('users', 'UserController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Categories
     */
    Route::get('categories/sort', ['as' => 'admin.categories.sort', 'uses' => 'CategoryController@sort']);
    Route::get('categories/search', ['as' => 'admin.categories.search', 'uses' => 'CategoryController@search']);
    Route::resource('categories', 'CategoryController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Posts
     */
    Route::get('posts/sort', ['as' => 'admin.posts.sort', 'uses' => 'PostController@sort']);
    Route::get('posts/search', ['as' => 'admin.posts.search', 'uses' => 'PostController@search']);
    Route::resource('posts', 'PostController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Tags
     */
    Route::get('tags/sort', ['as' => 'admin.tags.sort', 'uses' => 'TagController@sort']);
    Route::get('tags/search', ['as' => 'admin.tags.search', 'uses' => 'TagController@search']);
    Route::resource('tags', 'TagController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);


});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Category extends Model
{
    use Searchable;

    protected $fillable = [
        'name',
        'parent_category_id'
    ];

    public function category()
    {
        return $this->hasOne('App\Models\Category', 'id', 'parent_category_id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Repositories\CategoryRepository;

class CategoryController extends Controller
{
    protected $category;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->category = $categoryRepository;
    }

    public function index ()
    {
        $result = $this->category->index(10);

        return view('admin.categories.index', $result);
    }

    public function create()
    {
        $categories = $this->category->createCategory();

        return view('admin.categories.create', $categories);
    }

    public function store(CategoryRequest $categoryRequest)
    {
        $category_id = $this->category->storeCategory($categoryRequest);

        return redirect()->route('admin.categories.edit', ['id' => $category_id]);
    }

    public function edit($id)
    {
        $result = $this->category->edit($id);

        return view('admin.categories.edit', $result);
    }

    public function update(CategoryRequest $categoryRequest, $id)
    {
        $result = $this->category->updateCategory($categoryRequest, $id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Данные успешно изменены!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось внести изменения!');
        }

        return $redirect;
    }

    public function destroy($id)
    {
        if ($this->category->delete($id)) {
            $redirect = redirect()->back()->with('success', 'Категория удалена!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось удалить категорию!');
        }

        return $redirect;
    }

    public function sort(Request $request)
    {
        $result = $this->category->sort($request, 10, 'category');

        return view('admin.categories.index', $result);
    }

    public function search(Request $request)
    {
        $result = $this->category->search($request);

        return view('admin.categories.index', $result);
    }
    
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.categories.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Создание категории </h5>
                    </div>

                    <div class="panel-body">

                        <div class="form-group">
                            <label>Название категории</label>
                            <input type="text" class="form-control" name="name" placeholder="name">
                            @if ($errors->has('name'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Родительская категория</label>
                            <select name="parent_category_id" class="bootstrap-select" data-live-search="true" data-width="100%">
                                <option value="0">По умолчанию</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('parent_category_id'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('parent_category_id') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.categories.update', ['id' => $category->id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Редактирование категории </h5>
                    </div>

                    <div class="panel-body">

                        <div class="form-group">
                            <label>Название категории</label>
                            <input type="text" class="form-control" name="name" placeholder="name" value="{{ $category->name }}">
                            @if ($errors->has('name'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Родительская категория</label>
                            <select name="parent_category_id" class="bootstrap-select" data-live-search="true" data-width="100%">
                                <option  value="0" selected>Родительская</option>
                                @foreach($categories as $cat)
                                    @if($cat->id == $category->parent_category_id)
                                        <option  value="{{ $cat->id }}" selected>{{ $cat->name }}</option>
                                    @else
                                        <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @if ($errors->has('parent_category_id'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('parent_category_id') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@push('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>

    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/core.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/effects.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/interactions.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/extensions/cookie.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/switchery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/trees/fancytree_all.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/trees/fancytree_childcounter.js') }}"></script>

    <script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_notifications_other.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/datatables_basic.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_inputs.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/extra_trees.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js') }}"></script>
@endpush

@section('content')

    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="row">

                <div class="col-md-3">
                    <h5 class="panel-title"><a href="{{ route('admin.categories.index') }}">Категории</a></h5>
                </div>

                <div class="col-md-6">
                    <a href="{{ route('admin.categories.create') }}" class="btn btn-success">Новая категория</a>
                </div>

                <div class="col-md-3">
                    <form action="{{ route('admin.categories.search') }}" method="GET">
                        <div class="has-feedback-left">
                            <input type="text" name="query" class="form-control" placeholder="{{ isset($query) ? $query : 'поиск' }}">
                            <div class="form-control-feedback">
                                <i class="icon-search4 text-size-base"></i>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.categories.sort', ['name' => 'id', 'type' => isset($type) ? $type : '']) }}">ID</a>
                    @else
                        ID
                    @endif
                </th>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.categories.sort', ['name' => 'name', 'type' => isset($type) ? $type : '']) }}">Name</a>
                    @else
                        Name
                    @endif
                </th>
                <th>Parent category</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($result as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>

                    @if(isset($category->category->name))
                        <td>{{ $category->category->name }}</td>
                    @else
                        <td>Это родительская категория</td>
                    @endif

                    <td>{{ $category->created_at }}</td>
                    <td>{{ $category->updated_at }}</td>
                    <td class="text-center">
                        <div class="media-right media-middle" style="float: right">
                            <ul class="icons-list icons-list-extended text-nowrap">
                                <li><a href="{{ route('admin.categories.edit', ['id' => $category->id]) }}" class="edit"><button class="btn btn-primary"><i class="icon-pencil5"></i></button></a></li>
                                <li>
                                    <form action="{{ route('admin.categories.destroy', ['id' => $category->id]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                        <button type="submit" class="btn btn-danger delete"><i class="icon-trash-alt"></i></button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>

        <div class="panel-footer">
            <div style="text-align: center">
                {{ $result->links() }}
            </div>
        </div>
    </div>
    <!-- /basic datatable -->

@endsection