routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function() {
    Route::get('/', ['as' => 'admin.index', 'uses' => 'AdminController@index']);

    /*
     * Users
     */
    Route::get('users/sort', ['as' => 'admin.users.sort', 'uses' => 'UserController@sort']);
    Route::get('users/search', ['as' => 'admin.users.search', 'uses' => 'UserController@search']);
    Route::resource('users', 'UserController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Categories
     */
    Route::get('categories/sort', ['as' => 'admin.categories.sort', 'uses' => 'CategoryController@sort']);
    Route::get('categories/search', ['as' => 'admin.categories.search', 'uses' => 'CategoryController@search']);
    Route::resource('categories', 'CategoryController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Posts
     */
    Route::get('posts/sort', ['as' => 'admin.posts.sort', 'uses' => 'PostController@sort']);
    Route::get('posts/search', ['as' => 'admin.posts.search', 'uses' => 'PostController@search']);
    Route::resource('posts', 'PostController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);

    /*
     * Tags
     */
    Route::get('tags/sort', ['as' => 'admin.tags.sort', 'uses' => 'TagController@sort']);
    Route::get('tags/search', ['as' => 'admin.tags.search', 'uses' => 'TagController@search']);
    Route::resource('tags', 'TagController', [
        'as' => 'admin',
        'expect' => ['show'],
    ]);


});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Tag extends Model
{
    use Searchable;

    protected $fillable = [
        'name'
    ];

    public function posts()
    {
        return $this->belongsToMany('App\Models\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\TagRepository;

class TagController extends Controller
{
    protected $tag;

    public function __construct(TagRepository $tagRepository)
    {
        $this->tag = $tagRepository;
    }

    public function index(Request $request)
    {
        $values = $this->tag->index(10);

        return view('admin.tags.index', $values);
    }

    public function create()
    {
        return view('admin.tags.create');
    }

    public function store(Request $request)
    {
        $result = $this->tag->store($request);

        if (!empty($result)) {
            $redirect = redirect()->route('admin.tags.index')->with('success', 'Тег успешно создан!');
        } else {
            $redirect = redirect()->route('admin.tags.index')->with('error', 'Не удалось создать тег!');
        }

        return $redirect;
    }

    public function edit($id)
    {
        $tag = $this->tag->edit($id);

        return view('admin.tags.edit', $tag);
    }

    public function update(Request $request, $id)
    {
        $result = $this->tag->update($request->all(), $id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Тег изменен!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось изменить тег!');
        }

        return $redirect;
    }

    public function destroy($id)
    {
        $result = $this->tag->delete($id);

        if ($result) {
            $redirect = redirect()->back()->with('success', 'Тег удален!');
        } else {
            $redirect = redirect()->back()->with('error', 'Не удалось удалить тег!');
        }

        return $redirect;
    }

    public function sort(Request $request)
    {
        $result = $this->tag->sort($request, 10);

        return view('admin.tags.index', $result);
    }

    public function search(Request $request)
    {
        $result = $this->tag->search($request, 10);

        return view('admin.tags.index', $result);
    }

}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.tags.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Создание тега</h5>
                    </div>

                    <div class="panel-body">

                        <div class="form-group">
                            <label>Название тега</label>
                            <input type="text" class="form-control" name="name" placeholder="name">
                            @if ($errors->has('name'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.app')

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/uploader_bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js') }}"></script>
@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">

            <!-- Basic layout-->
            <form action="{{ route('admin.tags.update', ['id' => $tag->id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('put') }}
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title">Изменение тега</h5>
                    </div>

                    <div class="panel-body">

                        <div class="form-group">
                            <label>Название тега</label>
                            <input type="text" class="form-control" name="name" placeholder="name" value="{{ $tag->name }}">
                            @if ($errors->has('name'))
                                <span class="alert-danger">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Сохранить <i class="icon-arrow-right14 position-right"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>
    </div>

@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.app')

@push('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_notifications_other.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/datatables_basic.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/form_inputs.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js') }}"></script>
@endpush

@section('content')

    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="row">

                <div class="col-md-3">
                    <h5 class="panel-title"><a href="{{ route('admin.tags.index') }}">Теги</a></h5>
                </div>

                <div class="col-md-6">
                    <a href="{{ route('admin.tags.create') }}" class="btn btn-success">Новый тег</a>
                </div>

                <div class="col-md-3">
                    <form action="{{ route('admin.tags.search') }}" method="GET">
                        <div class="has-feedback-left">
                            <input type="text" name="query" class="form-control" placeholder="{{ isset($query) ? $query : 'поиск' }}">
                            <div class="form-control-feedback">
                                <i class="icon-search4 text-size-base"></i>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.tags.sort', ['name' => 'id', 'type' => isset($type) ? $type : '']) }}">ID</a>
                    @else
                        ID
                    @endif
                </th>
                <th>
                    @if(!isset($query) || isset($type))
                        <a href="{{ route('admin.tags.sort', ['name' => 'name', 'type' => isset($type) ? $type : '']) }}">Name</a>
                    @else
                        Name
                    @endif
                </th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($result as $tag)
                <tr>
                    <td>{{ $tag->id }}</td>
                    <td>{{ $tag->name }}</td>
                    <td>{{ $tag->created_at }}</td>
                    <td>{{ $tag->updated_at }}</td>
                    <td class="text-center">
                        <div class="media-right media-middle" style="float: right">
                            <ul class="icons-list icons-list-extended text-nowrap">
                                <li><a href="{{ route('admin.tags.edit', ['id' => $tag->id]) }}" class="edit"><button class="btn btn-primary"><i class="icon-pencil5"></i></button></a></li>
                                <li>
                                    <form action="{{ route('admin.tags.destroy', ['id' => $tag->id]) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('delete') }}
                                        <button type="submit" class="btn btn-danger delete"><i class="icon-trash-alt"></i></button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>

        <div class="panel-footer">
            <div style="text-align: center">
                {{ $result->links() }}
            </div>
        </div>
    </div>
    <!-- /basic datatable -->

@endsection